### ISSUE TITLE
Could not find a declaration file for module '@baronha/react-native-multiple-image-picker'.

### ISSUE THREAD

**Issue by Marvin3Benz** [baronha/react-native-multiple-image-picker#21]
IDE: VScode

Language: Typescript

Workflow: Expo (SDK 41)

How it occurred: 
  1. `yarn add @baronha/react-native-multiple-image-picker` 
  2. write `import MultipleImagePicker from "@baronha/react-native-multiple-image-picker";` in my code
  3. raised a problem

Problem detail:
Could not find a declaration file for module '@baronha/react-native-multiple-image-picker'. '/myproject/node_modules/@baronha/react-native-multiple-image-picker/lib/commonjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/baronha__react-native-multiple-image-picker` if it exists or add a new declaration (.d.ts) file containing `declare module '@baronha/react-native-multiple-image-picker';

**Comment by Aryan6290** [comment]
Any solution?

**Comment by baronha** [comment]
Sorry. Perhaps this error lies in your use of Expo.

**Comment by Aryan6290** [comment]
I am using a React Native CLI Project with Typescript

**Comment by baronha** [comment]
you can try ```rm -rf node_modules && yarn && cd ./ios && pod install && cd ..```

**Comment by James-Firth** [comment]
Hi I am getting the same issue, I am using the Expo Bare workflow.

I am not a Typescript expert, but I think it may be because the `index.d.ts` file is in the `src` folder but when you import the library it looks inside `lib/commonjs`?

Thank you for your work!

![image](https://user-images.githubusercontent.com/485809/125373660-2a7fc100-e34b-11eb-9814-920fefd6d008.png)
![image](https://user-images.githubusercontent.com/485809/125373802-5c912300-e34b-11eb-93be-6c2c3d583c2b.png)
